title: Cesar Eduardo Cruz Cabrera
logo: /assets/img/20250405_202407.jpg
description: Científico de Datos con habilidades en el desarrollo de modelos predictivos, análisis exploratorio de datos y creación de visualizaciones interactivas. Me especializo en trabajar con datos estructurados y no estructurados, aplicando técnicas de aprendizaje automático supervisado y no supervisado, como regresión, clasificación y clustering. Manejo con soltura herramientas como Python, SQL y bibliotecas de visualización, y sé cómo transformar datos en ideas valiosas para la toma de decisiones.
# show_downloads: true
theme: jekyll-theme-minimal
