title: Cesar Eduardo Cruz Cabrera
logo: /assets/img/20250524_093650_0000.png
description: Científico de Datos con habilidades en el desarrollo de modelos predictivos, análisis exploratorio de datos y visualizaciones interactivas. Me especializo en trabajar con datos estructurados y no estructurados, aplicando técnicas de aprendizaje automático supervisado y no supervisado, como regresión, clasificación y clustering.
# show_downloads: true
theme: jekyll-theme-minimal
